name: Selenium Test Suite

on:
  push:
    branches:
        -main
  pull_request:
    branches:
        -main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        # Grabs your repo files for the CI server

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
        # Installs Python 3.11 on the runner (GitHub’s virtual machine)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        # Recreates your local environment (installs Selenium + Pytest)

      - name: Run Selenium Tests
        run: |
          pytest -v
        # Runs your tests and displays detailed results
